app/urls.py
from django.urls import path
from .views import *
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    # Admin URLs
path("home/admin", AdminHomeView.as_view(), name="admin-home"),
path("register/admin", AdminRegistrationView.as_view(), name="admin-registration"),
path('login/admin', AdminLoginView.as_view(), name='admin-login'),
path('add/locations', AddLocationView.as_view(), name="add-locations"),
path('approval/<int:pk>', approve_mechanic, name="approve"),

# Mechanic URLs
path("mechanic/home", MechnaicHomeView.as_view(), name="mechanic_home"),
path("add/profile/<int:pk>", MechanicProfileAddView.as_view(), name="add-profile"),
path("profile/view/<int:pk>", MechanicProfileDetailView.as_view(), name="view-profile"),
path("profile/<int:pk>/update", MechanicprofileUpdateView.as_view(), name="update-profile"),
path('pending', PendingMechanicView.as_view(), name="pending-list"),
path('my-requests/', MechanicReqListView.as_view(), name='mechanic_requests'),
path('mechanicapproval/<int:pk>', update_status, name="mech-approve"),
path('feedback-list/', FeedbackListView.as_view(), name='feedback_list'),
path('create-bill-payment/<int:pk>/', BillPaymentCreateView.as_view(), name='create_bill_payment'),


# User URLs
path("user/home", UserHomeView.as_view(), name="user_home"),
path("user/registration", RegistrationView.as_view(), name="user_registration"),
path("useradd/profile/<int:pk>", UserProfileAddView.as_view(), name="useradd-profile"),
path("userprofile/view/<int:pk>", UserProfileDetailView.as_view(), name="userview-profile"),
path("userprofile/update/<int:pk>", UserProfileUpdateView.as_view(), name="userupdate-profile"),
path('approved-mechanics/', ApprovedMechanicListView.as_view(), name='approved_mechanics'),
path("create/req/<int:mechanic_id>", ReqToMechanicCreateView.as_view(), name="create_req"),
path('requests/', UserRequestsListView.as_view(), name='user_requests'),
path('feedback/<int:pk>', FeedBackCreateView.as_view(), name='feedback_form'),
path('bill-payment/<int:pk>/', bil_payment, name='bill_payment'),
path('cars/available/', RentCarListView.as_view(), name='available_cars'),
path('reserve/<int:pk>/', ReserveCarView.as_view(), name='reserve_car'),
path('reservations/', UserReservationListView.as_view(), name='user_reservation_list'),
path('update_reservation/<int:pk>/',update_reservation, name='update_reservation'),

#car renter URLS
path("car/home", CarRenterHomeView.as_view(), name="car_home"),
path('car_renter_profile/<int:pk>', CarRenterProfileCreateView.as_view(), name='car_renter_profile'),
path('car_renter_profile/update/<int:pk>', CarRenterProfileUpdateView.as_view(), name='car_renter_profile_update'),
path('car_renter_profile/view/', CarRenterProfileDetailView.as_view(), name='car_renter_profile_view'),
path('rent_car/', RentCarCreateView.as_view(), name='rent_car_create'),
path('rent_car/update/<int:pk>/', RentCarUpdateView.as_view(), name='rent_car_update'),
path('rentcars/', UserRentCarListView.as_view(), name='rentcar_list'),
path('my_reservations/', CarOwnerReservationsListView.as_view(), name='car_owner_reservations'),

# path('reservation/<int:pk>', ReservationDetailView.as_view(), name='reservation_detail'),


# Common URLs
path("",HomeView.as_view(),name="home"),
path('login/', LoginView.as_view(), name='login'),
path('logout/', LogoutView, name='logout'), 
path('change-password/', CustomPasswordChangeView.as_view(), name='change_password'),
path("payment/sucess/",PaymentSuccessView.as_view(),name="payment"),
path('search/',mechanic_search, name='mechanic_search'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class Location(models.Model):
    name=models.CharField(max_length=200)

    def __str__(self):
        return self.name

class User(AbstractUser):
    ROLE_CHOICES = [
        ("admin","Admin"),
        ("user", "User"),
        ("mechanic", "Mechanic"),
        ("car_renter","Car Renter")
    ]
    role = models.CharField(max_length=200, choices=ROLE_CHOICES, default="user")

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="user_profile")
    name=models.CharField(max_length=20)
    address = models.CharField(max_length=200)
    phone = models.CharField(max_length=200)
    dob = models.DateField(null=True)
    profile_pic = models.ImageField(upload_to="userprofile",default='static/images/profile/default.jpg', blank=True, null=True)

    def __str__(self):
        return self.user.username


class MechanicProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="mechanic_profile")
    name=models.CharField(max_length=100)
    location = models.ForeignKey(Location, on_delete=models.CASCADE, related_name="mechanic_location")
    phone = models.CharField(max_length=200)
    dob = models.DateField(null=True)
    skills = models.TextField()
    experience = models.CharField(max_length=200)
    STATUS_CHOICES = [
        ("approved", "Approved"),
        ("pending", "Pending"),
    ]
    status = models.CharField(max_length=200, choices=STATUS_CHOICES, default="pending")
    SPECIALIZATION_CHOICES = [
        ("two_wheeler", "Two Wheeler"),
        ("four_wheeler", "Four Wheeler"),
        ("heavy_vehicle", "Heavy Vehicle"),
    ]
    specialized_in = models.CharField(max_length=200, choices=SPECIALIZATION_CHOICES)
    bio = models.CharField(max_length=200)
    profile_pic = models.ImageField(upload_to="mech_pics",default='static/images/profile/default.jpg', blank=True, null=True)

    def __str__(self):
        return self.user.username


class ReqToMechanic(models.Model):
    user=models.ForeignKey(UserProfile,on_delete=models.CASCADE,related_name="req_profile")
    mechanic=models.ForeignKey(MechanicProfile,on_delete=models.CASCADE,related_name="req_profile")
    discription=models.CharField(max_length=200)
    phone=models.IntegerField()
    location=models.ForeignKey(Location,on_delete=models.CASCADE,related_name="req_location")
    STATUS_CHOICES = [
        ("completed", "Completed"),
        ("pending", "Pending"),
    ]
    status = models.CharField(max_length=200, choices=STATUS_CHOICES, default="pending")


class Bill(models.Model):
    customer=models.ForeignKey(UserProfile,on_delete=models.CASCADE)
    mechanic=models.ForeignKey(MechanicProfile,on_delete=models.CASCADE)
    req=models.ForeignKey(ReqToMechanic,on_delete=models.CASCADE)
    payment=models.PositiveBigIntegerField()
    STATUS_CHOICES = [
        ("completed", "Completed"),
        ("pending", "Pending"),
    ]
    status = models.CharField(max_length=200, choices=STATUS_CHOICES, default="pending")


class FeedBack(models.Model):
    user=models.ForeignKey(UserProfile,on_delete=models.CASCADE,related_name="feedback_userprofile")
    request=models.ForeignKey(ReqToMechanic,on_delete=models.CASCADE,related_name="feedback_req",null=True)
    mechanic=models.ForeignKey(MechanicProfile,on_delete=models.CASCADE,related_name="feedback_mechanicprofile")
    text=models.CharField(max_length=200)
    options=(
        ("1","1"),
        ("2","2"),
        ("3","3"),
        ("4","4"),
        ("5","5"),
    )
    rating=models.CharField(max_length=200,choices=options,default="5")
    date=models.DateTimeField(auto_now_add=True)

class CarRenterProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="carrental_profile")
    name=models.CharField(max_length=20)
    address = models.CharField(max_length=200)
    phone = models.CharField(max_length=200)
    dob = models.DateField(null=True)
    bio = models.CharField(max_length=200)
    profile_pic = models.ImageField(upload_to="pic_pics",default='static/images/profile/default.jpg', blank=True, null=True)

    def __str__(self):
        return self.user.username

class RentCar(models.Model):
    owner=models.ForeignKey(CarRenterProfile,on_delete=models.CASCADE,related_name="carrental_profile")
    name=models.CharField(max_length=200)
    price=models.PositiveBigIntegerField()
    car_img=models.ImageField(upload_to="car_pics",default='static/images/car/default.jpg', blank=True, null=True)
    discription=models.CharField(max_length=200)
    STATUS_CHOICES = [
        ("available", "Available"),
        ("not_available", "Not Available"),
    ]
    status = models.CharField(max_length=200, choices=STATUS_CHOICES, default="available")
    def __str__(self):
        return self.name

class CarReserve(models.Model):
    customer=models.ForeignKey(UserProfile,on_delete=models.CASCADE)
    car=models.ForeignKey(RentCar,on_delete=models.CASCADE)
    start_date=models.DateField()
    end_date=models.DateField()
    checked_out = models.BooleanField(default=False)
    created_on = models.DateTimeField(auto_now_add=True)
    total_price = models.DecimalField(max_digits=10, decimal_places=2, default=0.0)

    class Meta:
        ordering = ['-created_on']

app/templates/add_location.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Add Location</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <style>
        .sidebar {
            width: 250px;
            background-color: #343a40;
            padding: 20px;
            color: #fff;
            height: 100vh;
        }

        .main-content {
            flex: 1;
            padding: 20px;
        }

        .dashboard-heading {
            text-align: center;
            color: #fff;

        }

        .dashboard-item {
            margin-bottom: 20px;
        }

        .dashboard-item a {
            color: #fff;
            text-decoration: none;
            display: block;
            padding: 10px;
            border-radius: 5px;
        }

        .dashboard-item a:hover {
            background-color: #495057;
        }

        .container {
            display: flex;
            justify-content: center;
            align-items: center;
            height: 90vh;
        }
        
    </style>
</head>

<body>
    <div class="container-fluid">
        <div class="row">
            <!-- Sidebar -->
            <div class="sidebar">
                <a href="{% url 'admin-home' %}" class="dashboard-heading"><h1 class="text-white">Admin Dashboard</h1></a>              
                  <div class="dashboard-item">
                    <a href="{% url 'add-locations' %}" class="mt-5">Add Location</a>
                </div>
                <div class="dashboard-item">
                    <a href="{% url 'pending-list' %}">Pending Requests</a>
                </div>
                <div class="dashboard-item">
                    <a href="{% url 'change_password' %}">Change Password</a>
                </div>
                <div class="dashboard-item">
                    <a href="{% url 'logout' %}">Logout</a>
                </div>
            </div>
            <!-- Main Content -->
            <div class="col main-content bg-white">
                <div class="container">
                    <form class="form-control w-50 h-45 shadow" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="text-center">
                            <span class="h2 fw-bold">ADD LOCATION</span>
                        </div>
                        <div class="mt-4 mb-4">
                            <input class="form-control" placeholder="Enter Location" type="text" name="name" id="">
                        </div>
                        <div class="text-center mb-3 mt-3">
                            <button class="btn btn-primary mt-3">Add</button>
                            <button class="btn btn-danger mt-3">Cancel</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</body>

</html>

app/templates/admin_login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
    
</head>

<body>
    <section>

        <div class="box">

            <div class="square" style="--i:0;"></div>
            <div class="square" style="--i:1;"></div>
            <div class="square" style="--i:2;"></div>
            <div class="square" style="--i:3;"></div>
            <div class="square" style="--i:4;"></div>
            <div class="square" style="--i:5;"></div>

            <div class="container">
                <div class="form">
                    <h2 class="text align-items-center">Admin Login</h2>
                    <form action="" method="post">
                        {%csrf_token%}
                        <div class="inputBx">
                            <input name="username" type="text" required="required">
                            <span>Username</span>
                            <i class="fas fa-user-circle"></i>
                        </div>
                        <div class="inputBx password">
                            <input id="password-input" type="password" name="password" required="required">
                            <span>Password</span>
                            <a href="#" class="password-control" onclick="return show_hide_password(this);"></a>
                            <i class="fas fa-key"></i>
                        </div>
                        <label class="remember"><input type="checkbox">
                            Remember</label>
                        <div class="inputBx">
                            <input type="submit" value="Log in">
                        </div>
                    </form>
                    <p>Forgot password? <a href="#">Click Here</a></p>
                    <p>Don't have an account <a href="{%url 'admin-registration'%}">Sign up</a></p>
                </div>
            </div>

        </div>
    </section>

</body>
<script src="{% static 'js/login.js'%}"></script>

</html>

app/templates/approved_mechanic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body class="vh-100" style="background: rgb(241, 239, 240);
background: radial-gradient(circle, rgb(248, 247, 247) 0%, rgb(76, 76, 77) 100%);">
    <div class="container mt-5">
        <div class="text-center my-3">
            <h1>APPROVED MECHANICS</h1>
        </div>
    <!-- <ul>
        {% for mechanic in mechanics %}
        <li>{{ mechanic.name }}</li>
        <form action="{%url 'create_req' mechanic.id %}" method="post">
            {%csrf_token%}
            <button type="submit">Request</button>
        </form>
        {% endfor %}
    </ul> -->


        <div class="row">
            {% for mechanic in mechanics %}
            <div class="col-sm-6 mb-3 mb-sm-0 g-3">
            <form action="{%url 'create_req' mechanic.id %}" class="card">
                {%csrf_token%}
                <div class="card-body border border-0 text-center shadow">
                    <h2 class="card-title">{{mechanic.name}}</h2>
                    <p class="card-text">{{mechanic.location}}</p>
                    <p class="card-text">{{mechanic.phone}}</p>
                    <p class="card-text">{{mechanic.skills}}</p>
                    <p class="card-text">{{mechanic.experience}}</p>
                    <button type="submit" class="btn btn-primary">Send Request</button>
                </div>
            </form>
            </div>
            {% endfor %}
        </div>
    </div>
</body>
</html>

app/templates/car_renter_register.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>CarRenter Registeration</title>
</head>

<body>
    <form action="" method="post">
        {%csrf_token%}
        {{form.as_p}}
        <button type="submit">Register</button>
    </form>
</body>

</html>

app/templates/feedback_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

</head>
<body><body class="vh-100" style="background: rgb(241, 239, 240);
    background: radial-gradient(circle, rgb(248, 247, 247) 0%, rgb(31, 30, 32) 100%);">
        <div class="container mt-5">
            <div class="form-control border-0 p-5 bg-white bg-opacity-50" action="">
                <div class="text-center my-3">
                    <div class="text-center my-3">
                    </div>
    
    
    <h1>Feedback List</h1>
    <ul>
        {% for feedback in feedback_list %}
        <li>{{ feedback.text }} - Rating: {{ feedback.rating }}</li>
        {% empty %}
        <li>No feedback found.</li>
        {% endfor %}
    </ul>
</body>
</html>

app/templates/home.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ORVBA Home</title>
    <link rel="stylesheet" href="{% static 'css/navbar.css'%}">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous"></head>
<body>

<nav class="navbar navbar-expand-lg bg-body-tertiary  ">
    <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo03"
            aria-controls="navbarTogglerDemo03" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="#">
            <img src="{% static 'images/logo.png' %}" alt="logo" srcset="" width="150">
        </a>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo03">
            <div class="d-flex gap-3 ms-auto me-3 cont">
                <div class="nav-item it">
                    <a class="nav-link" href="">Home</a>
                </div>
                <!-- <div class="nav-item it">
                    <a class="nav-link" href="">Shop</a>
                </div> -->
                <div class="it nav-item">
                    <a class="nav-link" href="{%url 'admin-login'%}">Admin Login</a>
                </div>
                <div class="it nav-item">
                    <a class="nav-link" href="{%url 'login'%}">Login</a>
                </div>
            </div>
        </div>
    </div>
</nav>
<div class="container-fluid  m-0 p-0">
    <div class="img-container container-fluid  m-0 p-0">
        <img src="{% static 'images/banner.jpg' %}" alt="Image" class="img img-fluid m-0 p-0" width="100%">
        <div class="text-overlay">
            <h1 text-bold>ONROAD VEHICLE BREAKDOWN ASSISTANCE</h1>
        </div>
    </div>
</div>
</body>
</html>

app/templates/mechanic_profile_update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

</head>
<body class="vh-100" style="background: rgb(241, 239, 240);
background: radial-gradient(circle, rgb(248, 247, 247) 0%, rgb(31, 30, 32) 100%);">


    <div class="container mt-5">
        <div class="form-control border-0 p-5 bg-white bg-opacity-50" action="" >
            <div class="text-center my-3">
                <span class="h1  fw-bold">MECH PROFILE UPDATE</span>
            </div>
    

        <form action="" method="post" enctype="multipart/form-data">
            {%csrf_token%}
                {{form.as_p}}
                <button type="submit">Update</button>
        </form>
    </div>
</body>
</html>

app/templates/mechanic_profile_view.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>mech profile view</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body class="vh-100" style="background: rgb(241, 239, 240);
background: radial-gradient(circle, rgb(248, 247, 247) 0%, rgb(31, 30, 32) 100%);">
    <div class="container">
        <div class="row justify-content-center">
            <div class="text-center my-3">
                <span class="h1  fw-bold">MECH PROFILE VIEW</span>
            </div>
            <div class="card" style="width: 18rem;">
                <img src="{{data.profile_pic.url}}" class="card-img-top" alt="..." width="300px" height="300px">
                <div class="card-body">
                    <h5 class="card-title">{{data.name}}</h5>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item">{{data.location}}</li>
                    <li class="list-group-item">{{data.phone}}</li>
                    <li class="list-group-item">{{data.dob}}</li>
                    <li class="list-group-item">{{data.skills}}</li>
                    <li class="list-group-item">{{data.experience}}</li>
                </ul>
                <!-- <div class="card-body">
                    <button type="submit" class="btn btn-primary">
                        <a href="{%url 'update-profile' data.user.id %}" class="text-white">Update</a></button>
                </div> -->
            </div>
        </div>
    </div>
    
</body>

</html>
>

app/templates/mechanic_req_list.html
<!-- <!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>

<body class="vh-100" style="background: rgb(241, 239, 240);
background: radial-gradient(circle, rgb(248, 247, 247) 0%, rgb(76, 76, 77) 100%);">

    <div class="container mt-5">
        <div class="form-control border-0 p-5 bg-white bg-opacity-50" action="">
            <div class="text-center my-3">
                <div class="text-center my-3">
                </div>




                <h1>Requests Made to You</h1>
                
                    <div class="row">
                        {% for request in requests %}
                        <div class="col-md-4 mb-3 mb-sm-0 ">
                            <div class="card" style="width: 18rem;">

                                <li>{{ request.discription }}</li>
                                {% if request.status != 'completed' %}
                                <form action="{% url 'mech-approve' request.id %}" method="post"
                                    enctype="multipart/form-data">
                                    {% csrf_token %}
                                    <button type="submit">completed</button>
                                </form>
                                {% endif %}
                                {% if not request.bill_set.exists %} 
                                <form action="{% url 'create_bill_payment' request.id %}" method="post">
                                    {% csrf_token %}
                                    <button type="submit">create bill</button>
                                </form>
                                {% endif %}
                                {% endfor %}
                            </div>
                        </div>
                    </div>
            </div>
        </div>
    </div>
                
</body>

</html> -->



<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>

<body class="vh-100" style="background: rgb(241, 239, 240);
background: radial-gradient(circle, rgb(248, 247, 247) 0%, rgb(76, 76, 77) 100%);">

    <div class="container mt-5">
        
            <div class="form-control border-0 p-5 bg-white bg-opacity-50" action="">
                <div class="text-center my-3">
                    <div class="text-center my-3">
            <h1>Requests Made By User</h1>
            
            {% for request in requests %}
            <div class="col-md-4 mb-3">
                <div class="card d-flex">
                    <div class="card-body">
                        <h5 class="card-title">{{ request.discription }}</h5>
                        {% if request.status != 'completed' %}
                        <form action="{% url 'mech-approve' request.id %}" method="post"
                            enctype="multipart/form-data">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-primary">Completed</button>
                        </form>
                        {% endif %}
                        {% if not request.bill_set.exists %} <!-- Check if bill is not created -->
                        <form action="{% url 'create_bill_payment' request.id %}" method="post">
                            {% csrf_token %}
                            <button type="submit" class="btn btn-success">Create Bill</button>
                        </form>
                        {% endif %}
                    </div>
                </div>
            </div>
            {% endfor %}
                    </div>
                </div>
            </div>
        
    </div>

</body>

</html>

app/templates/rent_car_update.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Car Renter</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
</head>
<body class="vh-100" style="background: rgb(241, 239, 240);
background: radial-gradient(circle, rgb(248, 247, 247) 0%, rgb(123, 241, 119) 100%);">
  <div class="container mt-5">
    <div class="form-control border-0 p-5 bg-white bg-opacity-50" action="" >
        <div class="text-center my-3">
            <span class="h1  fw-bold">UPDATE THE CARS</span>
        </div>


    <form action="" method="post" enctype="multipart/form-data">
        {%csrf_token%}
        {{form.as_p}}
        <button type="submit">Updated</button>
    </form>
</body>

</html>